In [ ]:
import torch
import numpy as np

In [3]:
tensor=torch.ones(4,4)
tensor[...,-1]=0
print(tensor)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


In [ ]:
t1 = torch.ones(2, 2)
t2 = torch.zeros(2, 2)

# torch.cat: 주어진 텐서들을 주어진 차원에 맞춰 합쳐주는 함수

t3 = torch.cat([t1, t2], dim=0)
t4 = torch.cat([t1, t2], dim=1)

print(t3)

print(t3.shape)

print(t4)

print(t4.shape)

# torch.stack: 주어진 텐서들을 새로운 차원으로 합쳐주는 함수, cat과 다르게 차원이 하나 더 추가된다
# https://pytorch.org/docs/stable/generated/torch.stack.html
t3 = torch.stack([t1, t2], dim=0)
t4 = torch.stack([t1, t2], dim=1)

print(t3)

print(t3.shape)

print(t4)

print(t4.shape)

# https://velog.io/@nochesita/PyTorch-torch.cat%EA%B3%BC-torch.stack%EC%9D%98-%EC%B0%A8%EC%9D%B4

In [4]:
# 1. torch.rand() : 0과 1 사이의 숫자를 균등하게 생성
# 2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
# https://bigdatadiary0819.tistory.com/60

y1 = tensor @ tensor.T
print('y1',y1)
y2 = tensor.matmul(tensor.T)
print('y2',y2)
y3 = torch.rand_like(y1)
print('y3',y3)
torch.matmul(tensor, tensor.T, out=y3)

y1 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3 tensor([[0.2922, 0.0380, 0.2018, 0.6523],
        [0.5348, 0.7503, 0.2164, 0.3012],
        [0.2245, 0.7571, 0.5566, 0.2830],
        [0.7791, 0.3784, 0.5574, 0.5718]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [5]:
z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)
z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor([[9.6822e-01, 4.0161e-02, 2.7655e-01, 1.6870e-01],
        [3.5494e-01, 9.9783e-01, 1.3596e-01, 3.4666e-04],
        [1.0692e-01, 1.3396e-01, 3.5912e-01, 9.3706e-01],
        [2.2386e-01, 8.1597e-01, 2.6958e-01, 7.9137e-01]])


tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])