In [1]:
import torch
import numpy as np
import math

In [3]:
tensor=torch.ones(4,4)
tensor[...,-1]=0
print(tensor)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


In [ ]:
t1 = torch.ones(2, 2)
t2 = torch.zeros(2, 2)

# torch.cat: 주어진 텐서들을 주어진 차원에 맞춰 합쳐주는 함수

t3 = torch.cat([t1, t2], dim=0)
t4 = torch.cat([t1, t2], dim=1)

print(t3)

print(t3.shape)

print(t4)

print(t4.shape)

# torch.stack: 주어진 텐서들을 새로운 차원으로 합쳐주는 함수, cat과 다르게 차원이 하나 더 추가된다
# https://pytorch.org/docs/stable/generated/torch.stack.html
t3 = torch.stack([t1, t2], dim=0)
t4 = torch.stack([t1, t2], dim=1)

print(t3)

print(t3.shape)

print(t4)

print(t4.shape)

# https://velog.io/@nochesita/PyTorch-torch.cat%EA%B3%BC-torch.stack%EC%9D%98-%EC%B0%A8%EC%9D%B4

In [4]:
# 1. torch.rand() : 0과 1 사이의 숫자를 균등하게 생성
# 2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
# https://bigdatadiary0819.tistory.com/60

y1 = tensor @ tensor.T
print('y1',y1)
y2 = tensor.matmul(tensor.T)
print('y2',y2)
y3 = torch.rand_like(y1)
print('y3',y3)
torch.matmul(tensor, tensor.T, out=y3)

y1 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3 tensor([[0.2922, 0.0380, 0.2018, 0.6523],
        [0.5348, 0.7503, 0.2164, 0.3012],
        [0.2245, 0.7571, 0.5566, 0.2830],
        [0.7791, 0.3784, 0.5574, 0.5718]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [5]:
z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)
z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor([[9.6822e-01, 4.0161e-02, 2.7655e-01, 1.6870e-01],
        [3.5494e-01, 9.9783e-01, 1.3596e-01, 3.4666e-04],
        [1.0692e-01, 1.3396e-01, 3.5912e-01, 9.3706e-01],
        [2.2386e-01, 8.1597e-01, 2.6958e-01, 7.9137e-01]])


tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

In [3]:

# 무작위로 입력과 출력 데이터를 생성합니다
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

# 무작위로 가중치를 초기화합니다
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6
for t in range(2000):
  # 순전파 단계: 예측값 y를 계산합니다
  # y = a + b x + c x^2 + d x^3
  y_pred = a + b * x + c * x ** 2 + d * x ** 3

  # 손실(loss)을 계산하고 출력합니다
  loss = np.square(y_pred - y).sum()
  if t % 100 == 99:
    print(t, loss)

  # 손실에 따른 a, b, c, d의 변화도(gradient)를 계산하고 역전파합니다.
  grad_y_pred = 2.0 * (y_pred - y)
  grad_a = grad_y_pred.sum()
  grad_b = (grad_y_pred * x).sum()
  grad_c = (grad_y_pred * x ** 2).sum()
  grad_d = (grad_y_pred * x ** 3).sum()

  # 가중치를 갱신합니다.
  a -= learning_rate * grad_a
  b -= learning_rate * grad_b
  c -= learning_rate * grad_c
  d -= learning_rate * grad_d

print(f'Result: y = {a} + {b} x + {c} x^2 + {d} x^3')

99 46.19044270604725
199 35.128680743599425
299 27.34709990638791
399 21.870756998231933
499 18.015452469352255
599 15.300489638041116
699 13.38800261622937
799 12.040420806105914
899 11.090632538125684
999 10.421045856679438
1099 9.948886259067178
1199 9.615868927505996
1299 9.380940726049825
1399 9.215177427419775
1499 9.098194788617624
1599 9.015623430146661
1699 8.957331575632228
1799 8.916173748341446
1899 8.88710950126958
1999 8.866582573395371
Result: y = 0.007355542753702494 + 0.8577729321576373 x + -0.0012689535217734196 x^2 + -0.0934771947252661 x^3


In [12]:
print(x)
x.unsqueeze(-1).shape

tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])


torch.Size([2000, 1])

In [4]:
dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # GPU에서 실행하려면 이 주석을 제거하세요

# 무작위로 입력과 출력 데이터를 생성합니다
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

# 무작위로 가중치를 초기화합니다
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(2000):
  # 순전파 단계: 예측값 y를 계산합니다
  y_pred = a + b * x + c * x ** 2 + d * x ** 3

  # 손실(loss)을 계산하고 출력합니다
  loss = (y_pred - y).pow(2).sum().item()
  if t % 100 == 99:
    print(t, loss)

  # 손실에 따른 a, b, c, d의 변화도(gradient)를 계산하고 역전파합니다.
  grad_y_pred = 2.0 * (y_pred - y)
  grad_a = grad_y_pred.sum()
  grad_b = (grad_y_pred * x).sum()
  grad_c = (grad_y_pred * x ** 2).sum()
  grad_d = (grad_y_pred * x ** 3).sum()

  # 가중치를 갱신합니다.
  a -= learning_rate * grad_a
  b -= learning_rate * grad_b
  c -= learning_rate * grad_c
  d -= learning_rate * grad_d


print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

99 345.5351867675781
199 246.50732421875
299 176.63162231445312
399 127.31527709960938
499 92.50318145751953
599 67.92574310302734
699 50.57140350341797
799 38.31568145751953
899 29.659460067749023
999 23.54486083984375
1099 19.225114822387695
1199 16.173017501831055
1299 14.01637077331543
1399 12.492307662963867
1499 11.415184020996094
1599 10.653870582580566
1699 10.11573600769043
1799 9.735321998596191
1899 9.466384887695312
1999 9.276246070861816
Result: y = 0.022558296099305153 + 0.8545917868614197 x + -0.003891679225489497 x^2 + -0.09302470088005066 x^3


In [5]:
dtype=torch.float
device="cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)

x=torch.linspace(-math.pi, math.pi,2000,dtype=dtype)
y=torch.sin(x)

a=torch.randn((), dtype=dtype, requires_grad=True)
b=torch.randn((), dtype=dtype, requires_grad=True)
c=torch.randn((), dtype=dtype, requires_grad=True)
d=torch.randn((), dtype=dtype, requires_grad=True)

learning_rate=1e-6
for t in range(2000):
  y_pred=a+b*x+c*x**2+d*x**3
  loss=(y_pred-y).pow(2).sum()
  if t == 0 :  print('loss.shape',loss.shape)
  if t%100 == 99:
    print(t, loss.item())
    
  loss.backward()
  
  with torch.no_grad():
    a -= learning_rate*a.grad
    b -= learning_rate*b.grad
    c -= learning_rate*c.grad
    d -= learning_rate*d.grad
    
    a.grad=None
    b.grad=None
    c.grad=None
    d.grad=None

print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')    

loss.shape torch.Size([])
99 1407.66650390625
199 966.8894653320312
299 665.7542114257812
399 459.78387451171875
499 318.74285888671875
599 222.0520782470703
699 155.68994140625
799 110.0914306640625
899 78.72491455078125
999 57.12431335449219
1099 42.23255920410156
1199 31.9549617767334
1299 24.854345321655273
1399 19.943470001220703
1499 16.54364776611328
1599 14.187583923339844
1699 12.55324935913086
1799 11.418477058410645
1899 10.629875183105469
1999 10.081345558166504
Result: y = 0.033458977937698364 + 0.8409170508384705 x + -0.005772230215370655 x^2 + -0.09107958525419235 x^3


In [8]:
torch.full((),5)==torch.tensor(5)

tensor(True)

In [13]:
# 입력값과 출력값을 갖는 텐서들을 생성합니다.
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

# 이 예제에서, 출력 y는 (x, x^2, x^3)의 선형 함수이므로, 선형 계층 신경망으로 간주할 수 있습니다.
# (x, x^2, x^3)를 위한 텐서를 준비합니다.
p = torch.tensor([1, 2, 3])
xx = x.unsqueeze(-1).pow(p)

# 위 코드에서, x.unsqueeze(-1)은 (2000, 1)의 shape을, p는 (3,)의 shape을 가지므로,
# 이 경우 브로드캐스트(broadcast)가 적용되어 (2000, 3)의 shape을 갖는 텐서를 얻습니다. 
# Broadcastig은 두 텐서가 서로 다른 크기일 때, 자동으로 차원을 맞춰 연산을 수행할 수 있게 해주는 기능

# nn 패키지를 사용하여 모델을 순차적 계층(sequence of layers)으로 정의합니다.
# nn.Sequential은 다른 Module을 포함하는 Module로, 포함되는 Module들을 순차적으로 적용하여 
# 출력을 생성합니다. 각각의 Linear Module은 선형 함수(linear function)를 사용하여 입력으로부터
# 출력을 계산하고, 내부 Tensor에 가중치와 편향을 저장합니다.
# Flatten 계층은 선형 계층의 출력을 `y` 의 shape과 맞도록(match) 1D 텐서로 폅니다(flatten).
model = torch.nn.Sequential(
    torch.nn.Linear(3, 1),
    torch.nn.Flatten(0, 1)
)

# 또한 nn 패키지에는 주로 사용되는 손실 함수(loss function)들에 대한 정의도 포함되어 있습니다;
# 여기에서는 평균 제곱 오차(MSE; Mean Squared Error)를 손실 함수로 사용하겠습니다.
loss_fn = torch.nn.MSELoss(reduction='sum')

learning_rate = 1e-6
for t in range(2000):

  # 순전파 단계: x를 모델에 전달하여 예측값 y를 계산합니다. Module 객체는 __call__ 연산자를 
  # 덮어써서(override) 함수처럼 호출할 수 있도록 합니다. 이렇게 함으로써 입력 데이터의 텐서를 Module에 전달하여
  # 출력 데이터의 텐서를 생성합니다.
  y_pred = model(xx)

  # 손실을 계산하고 출력합니다. 예측한 y와 정답인 y를 갖는 텐서들을 전달하고,
  # 손실 함수는 손실(loss)을 갖는 텐서를 반환합니다.
  loss = loss_fn(y_pred, y)
  if t % 100 == 99:
    print(t, loss.item())

  # 역전파 단계를 실행하기 전에 변화도(gradient)를 0으로 만듭니다.
  model.zero_grad()

  # 역전파 단계: 모델의 학습 가능한 모든 매개변수에 대해 손실의 변화도를 계산합니다.
  # 내부적으로 각 Module의 매개변수는 requires_grad=True일 때 텐서에 저장되므로,
  # 아래 호출은 모델의 모든 학습 가능한 매개변수의 변화도를 계산하게 됩니다.
  loss.backward()

  # 경사하강법을 사용하여 가중치를 갱신합니다.
  # 각 매개변수는 텐서이므로, 이전에 했던 것처럼 변화도에 접근할 수 있습니다.
  with torch.no_grad():
    for param in model.parameters():
      param -= learning_rate * param.grad

# list의 첫번째 항목에 접근하는 것처럼 `model` 의 첫번째 계층(layer)에 접근할 수 있습니다.
linear_layer = model[0]

# 선형 계층에서, 매개변수는 `weights` 와 `bias` 로 저장됩니다.
print(f'Result: y = {linear_layer.bias.item()} + {linear_layer.weight[:, 0].item()} x + {linear_layer.weight[:, 1].item()} x^2 + {linear_layer.weight[:, 2].item()} x^3')

99 1279.6165771484375
199 855.3080444335938
299 572.9288940429688
399 384.9282531738281
499 259.7086181640625
599 176.26751708984375
699 120.63961029052734
799 83.5351333618164
899 58.773231506347656
999 42.23881149291992
1099 31.192058563232422
1199 23.806941986083984
1299 18.866796493530273
1399 15.559850692749023
1499 13.344681739807129
1599 11.859766006469727
1699 10.86358642578125
1799 10.194780349731445
1899 9.745405197143555
1999 9.44318962097168
Result: y = 0.014454414136707783 + 0.83636075258255 x + -0.002493626903742552 x^2 + -0.09043149650096893 x^3


In [17]:
# print(xx)
linear_layer.weight[0,0].item()

0.83636075258255